export const GET_MEMES_REQUEST = "GET_MEMES_REQUEST";
export const GET_MEMES_SUCCESS = "GET_MEMES_SUCCESS";
export const GET_MEMES_ERROR = "GET_MEMES_ERROR";
export const GET_MEMES_RESET = "GET_MEMES_RESET";

export const SET_TYPE = "SET_TYPE";

export const GET_MEME_INFO_REQUEST = "GET_MEME_INFO_REQUEST";
export const GET_MEME_INFO_SUCCESS = "GET_MEME_INFO_SUCCESS";
export const GET_MEME_INFO_ERROR = "GET_MEME_INFO_ERROR";
export const GET_MEME_INFO_RESET = "GET_MEME_INFO_RESET";
